/*TRABALHO 02 DE LINGUAGEM DE PROGRAMAÇAO DE BANCO DE DADOS*/
/*DEVELOPED BY GUILHERME COSTA*/

/* TABELA ENDEREÇO NORMALIZADA*/

/*EXCLUSAO DE TODAS AS TABELAS OBEDECENDO A INTEGRIDADE REFERENCIAL*/
DROP TABLE RECEBER;
DROP TABLE PAGAR;
DROP TABLE CLIENTE;
DROP TABLE FORNECEDOR;
DROP TABLE ENDERECO;
DROP TABLE ESTADO;
DROP TABLE FINANCEIRO;

/*CRIAÇAO DE TODAS AS TABELAS OBEDECENDO A INTEGRIDADE REFERENCIAL*/

CREATE TABLE ESTADO(
ID_ESTADO INTEGER NOT NULL,
NOME_ESTADO VARCHAR(30) NOT NULL,
UF VARCHAR(3) NOT NULL
);

CREATE TABLE ENDERECO(
ID_ENDERECO INTEGER NOT NULL,
TIPO VARCHAR(30) NOT NULL,
LOGRADOURO VARCHAR(100) NOT NULL,
CIDADE VARCHAR(100) NOT NULL,
FK_ID_ESTADO INTEGER NOT NULL
);

CREATE TABLE FINANCEIRO(
ID_FINANCEIRO INTEGER NOT NULL,
NUMERO INTEGER NOT NULL,
EMISSAO DATE NOT NULL,
VENCIMENTO DATE NOT NULL,
PAGAMENTO DATE NOT NULL,
VALOR NUMBER(12,2) NOT NULL,
JUROS NUMBER(12,2) NOT NULL,
MULTA NUMBER(12,2) NOT NULL,
DESCONTO NUMBER(12,2) NOT NULL,
TOTAL NUMBER(12,2) NOT NULL
);

CREATE TABLE CLIENTE(
ID_CLIENTE INTEGER NOT NULL,
NOME VARCHAR(100) NOT NULL,
CPF VARCHAR(15) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
DDD SMALLINT NOT NULL,
TELEFONE INTEGER NOT NULL,
FK_ID_ENDERECO INTEGER NOT NULL
);

CREATE TABLE FORNECEDOR(
ID_FORNECEDOR INTEGER NOT NULL,
NOME VARCHAR(100) NOT NULL,
RAZAO VARCHAR(100) NOT NULL,
CNPJ VARCHAR(20) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
DDD SMALLINT NOT NULL,
TELEFONE INTEGER NOT NULL,
FK2_ID_ENDERECO INTEGER NOT NULL
);

CREATE TABLE PAGAR(
FK_ID_FINANCEIRO INTEGER NOT NULL,
FK_ID_FORNECEDOR INTEGER NOT NULL,
BOLETO VARCHAR(50) NOT NULL
);

CREATE TABLE RECEBER(
FK2_ID_FINANCEIRO INTEGER NOT NULL,
FK_ID_CLIENTE INTEGER NOT NULL,
NOTA_FISCAL VARCHAR(50) NOT NULL
);

/*CRIAÇAO DE TODAS AS CHAVES PRIMARIAS UTILIZANDO O SUFIXO 'PK'*/

ALTER TABLE ESTADO
ADD CONSTRAINT PK_ID_ESTADO
    PRIMARY KEY (ID_ESTADO);
    
ALTER TABLE ENDERECO
ADD CONSTRAINT PK_ID_ENDERECO
    PRIMARY KEY (ID_ENDERECO);

ALTER TABLE FINANCEIRO
ADD CONSTRAINT PK_ID_FINANCEIRO
    PRIMARY KEY (ID_FINANCEIRO);
    
ALTER TABLE CLIENTE
ADD CONSTRAINT PK_ID_CLIENTE
    PRIMARY KEY (ID_CLIENTE);

ALTER TABLE FORNECEDOR
ADD CONSTRAINT PK_ID_FORNECEDOR
    PRIMARY KEY (ID_FORNECEDOR);

/*CRIAÇAO DE TODAS AS CHAVES SECUNDARIAS*/

ALTER TABLE CLIENTE
ADD CONSTRAINT FK_ID_ENDERECO
    FOREIGN KEY (FK_ID_ENDERECO)
    REFERENCES ENDERECO(ID_ENDERECO);
    
ALTER TABLE FORNECEDOR
ADD CONSTRAINT FK2_ID_ENDERECO
    FOREIGN KEY (FK2_ID_ENDERECO)
    REFERENCES ENDERECO(ID_ENDERECO);
    
ALTER TABLE ENDERECO
ADD CONSTRAINT FK_ID_ESTADO
    FOREIGN KEY (FK_ID_ESTADO)
    REFERENCES ESTADO(ID_ESTADO);
    
ALTER TABLE RECEBER
ADD CONSTRAINT FK2_ID_FINANCEIRO
    FOREIGN KEY (FK2_ID_FINANCEIRO)
    REFERENCES FINANCEIRO(ID_FINANCEIRO);
    
ALTER TABLE RECEBER 
ADD CONSTRAINT FK_ID_CLIENTE
    FOREIGN KEY (FK_ID_CLIENTE)
    REFERENCES CLIENTE(ID_CLIENTE);
    
ALTER TABLE PAGAR
ADD CONSTRAINT FK_ID_FINANCEIRO
    FOREIGN KEY (FK_ID_FINANCEIRO)
    REFERENCES FINANCEIRO(ID_FINANCEIRO);

ALTER TABLE PAGAR
ADD CONSTRAINT FK_ID_FORNECEDOR
    FOREIGN KEY (FK_ID_FORNECEDOR)
    REFERENCES FORNECEDOR(ID_FORNECEDOR);