/*TRABALHO 02 DE LINGUAGEM DE PROGRAMAÇAO DE BANCO DE DADOS*/
/*DEVELOPED BY GUILHERME COSTA*/

/*CRIAÇAO DA TRIGGER*/
CREATE OR REPLACE TRIGGER CALCULO_VALOR_TOTAL
BEFORE INSERT OR UPDATE ON FINANCEIRO
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
:new.TOTAL := (:new.VALOR + :new.JUROS + :new.MULTA - :new.DESCONTO);
COMMIT;
END;

